Vet clinic database: query and update animals table
yaredtekle022/Vet-clinic pull request #2
Opened 2023-08-26 05:47 UTC by yaredtekle022

### These list of activities were made

**Data insertion**

> Charmander, born on Feb 8th, 2020, currently weighs -11kg. He is not neutered and he has never tried to escape.

> Plantmon, born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.

>  Squirtle, born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to escape 3 times.

> Angemon, born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.

> Boarmon, born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.

>  Blossom, born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.

>  Ditto , born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to escape 4 times.

**Transactions**

> Updated animals table by setting the species column to unspecified
![Screenshot 2023-08-26 at 07 50 06](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/e44945fa-8a96-4c9e-a374-4510fc400045)

> ROLLBACK
![Screenshot 2023-08-26 at 07 50 48](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/844a7c48-989b-4526-8b08-2d83a864b964)

> Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
![Screenshot 2023-08-26 at 07 54 31](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/fb990ce2-0175-4ca7-b306-6aab82a003a1)

> Set the species column to pokemon for all animals that don't have species already set.

![Screenshot 2023-08-26 at 07 56 53](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/7a4bdbf1-aef5-4bd6-a022-226a36d5d93b)

> delete all records in the animals table, then roll back the transaction.
![Screenshot 2023-08-26 at 08 06 03](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/66eac05b-b28a-4e1f-a99e-d042652d40f0)

> ROLBACK

![Screenshot 2023-08-26 at 08 13 39](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/5b30477c-23f1-484e-a254-dd9176e08e0f)

 Delete all animals born after Jan 1st, 2022
![Screenshot 2023-08-26 at 08 16 32](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/76f27322-ebf7-4125-8d5c-69f71d612b0f)

Create a savepoint for the transaction
![Screenshot 2023-08-26 at 08 17 46](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/8d4d57e2-bc83-46af-b242-b2fd6fb4b7c1)

Update all animals' weight to be their weight multiplied by -1.
![Screenshot 2023-08-26 at 08 18 51](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/80d2aae7-578a-460c-af09-a9c41ad4224b)

Update all animals' weights that are negative to be their weight multiplied by -1
![Screenshot 2023-08-26 at 08 22 50](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/ff816b12-15ed-4a0d-9d2b-d91774b4ce03)

### Queries
Count number of animals
![Screenshot 2023-08-26 at 08 23 32](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/601d7b69-8341-4117-8c8a-5fb6a2f27c99)

Count the number of animals that have never escaped:
![Screenshot 2023-08-26 at 08 23 49](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/cafd7d74-cc45-4524-8472-990996433269)

Average weight of the animals:
![Screenshot 2023-08-26 at 08 24 04](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/44ad1288-dd71-4cdc-92b7-68e68fd551e4)

Escape attempts
![Screenshot 2023-08-26 at 08 24 56](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/fb2cb0d1-84a1-4042-8ea1-be447c6eecab)

Minimum and maximum weight of each type of animal:
![Screenshot 2023-08-26 at 08 25 26](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/1b05839b-dbb3-40cc-942c-652ac1023d9a)

Average number of escape attempts per animal type-born between 1990 and 2000?
![Screenshot 2023-08-26 at 08 25 51](https://github.com/yaredtekle022/Vet-clinic/assets/117394421/d44fa24e-100b-4718-8a98-bd8a19b7b260)

2023-08-26 07:01 UTC, zieeco requested changes
Hi @yaredtekle022,

<img height="200" src="https://media2.giphy.com/media/ehxq3SFXUxvtK2qDFs/giphy.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Great effort on querying your database ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +
- Hey, great job here, however, you have to select the species from the animals to verify that the change was made before rolling back the transaction. kindly update your query by adding the missing query below:

```sql
 SELECT species from animals;  -- this will verify that the change was made.
   // ROLLBACK;
```

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +
- In continuation of my observation, after making the changes, you should still select the species from the animals to also verify that the change was undone after rolling back the transaction. please, add this missing query after the rollback.
 
`SELECT species from animals;` -- verify that the  change was undone.

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +COMMIT;
- Hey, let's make a few adjustments to our query. From the project requirement in the image below:

![image](https://github.com/yaredtekle022/Vet-clinic/assets/59397159/4034e3b1-ca92-4999-8bc2-c8f86b31f316)

You should make the commit after adding the two queries for this part of the transaction, however, you've committed before completing the remaining query. please, let's make the improvement on following the project requirements as much as we can.

   - From your code, remove line 20 and line 22.
   - then update line 27 from `COMMIT` to `SELECT species from animals;`  to verify that the change was made.
   - After, you may now `COMMIT` the changes to the database.
   - Furthermore, you can now verify the changes have been persisted in the database by selecting the species from the database `SELECT species from animals;`

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +
- Hey, let's try to fully implement this part of the project requirement as highlighted in the image in red below:

![image](https://github.com/yaredtekle022/Vet-clinic/assets/59397159/158d7dda-5be3-45ff-a483-1d5ab5594d40)

   - After the deletion, you want to still get the total count of the entities in the animals table. kindly update your query.
   
```sql
BEGIN;

   DELETE FROM animals WHERE ;
   SELECT COUNT(*) FROM ANIMALS;

   ROLLBACK;
   SELECT COUNT(*) FROM ANIMALS;
```

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +COMMIT;
- Hey, let's make a few adjustments to our query here to make it conform more to the project requirment, following a step-by-step approach. see the image to see the requirement better:

![image](https://github.com/yaredtekle022/Vet-clinic/assets/59397159/02f9a162-b252-488a-8d7d-8ee99e88d7ec)


   - Remove lines 38 and 40, these are still the sam transaction in progress, there's no need to commit now as you're not done with the transaction.
   - *Remove from lines 42 - 47*, as these are more like repetition and you don't need to commit yet as you're not done with the transaction.
   - Then, on your line 50, instead of `COMMIT`, you should rollback to your transaction 
   `ROLLBACK TO transaction_savepoint;` as you've done in line 52. Kindly note that you've already created the savepoint, so you should use the name instead of `ROLLBACK TO SAVEPOINT transaction_savepoint;` to 
`ROLLBACK TO transaction_savepoint;`
- Finally, you can now leave your line 53 which commits the changes to your database. `COMMIT`

Please, kindly ensure to update your code as much as you can following the instructions closely to better simplify your code and reduce the need for repetition.

2023-08-26 07:01 UTC, zieeco commented on queries.sql
> +GROUP BY species;
- Hey, let's update our query to start from the correct date so we get the accurate history. please, update your query and pay attention to the date.

```sql
 SELECT species, AVG(escape_attempts) FROM animals
   GROUP BY species
   WHERE  date_of_birth >= '1990/01/01' AND date_of_birth <= '2000/12/31';
```

2023-08-28 15:50 UTC, joel-kalema approved these changes
Hi @yaredtekle022 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-28 18:27 UTC, merged